name: Validate OSV JSON Schema

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: read

jobs:
  validate-osv-schema:
    name: Validate OSV Schema
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check for changes to OSV Schema
        id: check-for-changed-osv-schema
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
        with:
          files: |
            validation/schema.json
      - name: Validate OSV Schema
        if: steps.check-for-changed-osv-schema.outputs.any_changed == 'true'
        uses: dsanders11/json-schema-validate-action@ec60131eddf6f51ed0c737fdcd28616ae1a0e564 # v1.2.0
        with:
          # https://github.com/marketplace/actions/json-schema-validate#validating-schema
          schema: json-schema
          files: validation/schema.json
